# Generated by Django 4.2.10 on 2024-02-27 12:57

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django_handleref.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("django_fullctl", "0033_task_fullctl_tas_status_d88ee1_idx_and_more"),
        ("django_prefixctl", "0016_alter_asnset_slug_alter_prefixset_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="BGPMonitorTask",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("django_fullctl.task",),
            managers=[
                ("handleref", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="BGPMonitor",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created",
                    django_handleref.models.CreatedDateTimeField(
                        auto_now_add=True, verbose_name="Created"
                    ),
                ),
                (
                    "updated",
                    django_handleref.models.UpdatedDateTimeField(
                        auto_now=True, verbose_name="Updated"
                    ),
                ),
                ("version", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "Ok"),
                            ("pending", "Pending"),
                            ("deactivated", "Deactivated"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                        ],
                        default="ok",
                        max_length=12,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Primary alert notification email",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bgp_monitors",
                        to="django_fullctl.instance",
                    ),
                ),
                (
                    "prefix_set",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bgp_monitors",
                        to="django_prefixctl.prefixset",
                    ),
                ),
                (
                    "task_schedule",
                    models.OneToOneField(
                        blank=True,
                        help_text="The task schedule for this monitor",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_fullctl.taskschedule",
                    ),
                ),
            ],
            options={
                "verbose_name": "BGP Monitor",
                "verbose_name_plural": "BGP Monitors",
                "db_table": "prefixctl_bgp_monitor",
            },
            managers=[
                ("handleref", django.db.models.manager.Manager()),
            ],
        ),
    ]
